export default {
  params: [
    {
      stack_id: 9,
      name: "MySQL",
      total: 51,
      level_1: 31,
      level_2: 13,
      level_3: 1,
      level_4: 1,
      level_5: 5,
    },
    {
      stack_id: 3,
      name: "JavaScript",
      total: 49,
      level_1: 40,
      level_2: 5,
      level_3: 2,
      level_4: 1,
      level_5: 1,
    },
    {
      stack_id: 1,
      name: "Bootstrap",
      total: 34,
      level_1: 26,
      level_2: 4,
      level_3: 1,
      level_4: 1,
      level_5: 2,
    },
    {
      stack_id: 2236,
      name: "Adobe Photoshop",
      total: 33,
      level_1: 25,
      level_2: 5,
      level_3: 1,
      level_4: 1,
      level_5: 0,
    },
    {
      stack_id: 2225,
      name: "Sketch",
      total: 31,
      level_1: 19,
      level_2: 4,
      level_3: 3,
      level_4: 2,
      level_5: 0,
    },
    {
      stack_id: 1599,
      name: "Git",
      total: 31,
      level_1: 25,
      level_2: 3,
      level_3: 0,
      level_4: 1,
      level_5: 2,
    },
    {
      stack_id: 8,
      name: "HTML5",
      total: 30,
      level_1: 22,
      level_2: 4,
      level_3: 2,
      level_4: 2,
      level_5: 0,
    },
    {
      stack_id: 14,
      name: "Redis",
      total: 23,
      level_1: 15,
      level_2: 5,
      level_3: 0,
      level_4: 0,
      level_5: 2,
    },
    {
      stack_id: 2553,
      name: "CSS3",
      total: 19,
      level_1: 11,
      level_2: 6,
      level_3: 1,
      level_4: 1,
      level_5: 0,
    },
    {
      stack_id: 2554,
      name: "Linux",
      total: 19,
      level_1: 16,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 2,
    },
    {
      stack_id: 1607,
      name: "webpack",
      total: 18,
      level_1: 13,
      level_2: 4,
      level_3: 0,
      level_4: 1,
      level_5: 0,
    },
    {
      stack_id: 48,
      name: "Vue.js",
      total: 17,
      level_1: 8,
      level_2: 7,
      level_3: 1,
      level_4: 1,
      level_5: 0,
    },
    {
      stack_id: 2592,
      name: "Spring Cloud",
      total: 16,
      level_1: 12,
      level_2: 3,
      level_3: 0,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 17,
      name: "Java",
      total: 16,
      level_1: 12,
      level_2: 3,
      level_3: 0,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 1600,
      name: "Docker",
      total: 16,
      level_1: 11,
      level_2: 2,
      level_3: 2,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 5,
      name: "Node.js",
      total: 15,
      level_1: 13,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 42,
      name: "Less",
      total: 14,
      level_1: 10,
      level_2: 2,
      level_3: 1,
      level_4: 1,
      level_5: 0,
    },
    {
      stack_id: 2,
      name: "Nginx",
      total: 14,
      level_1: 8,
      level_2: 1,
      level_3: 0,
      level_4: 1,
      level_5: 4,
    },
    {
      stack_id: 52,
      name: "Spring",
      total: 14,
      level_1: 9,
      level_2: 4,
      level_3: 0,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 80,
      name: "Spring Boot",
      total: 13,
      level_1: 9,
      level_2: 3,
      level_3: 0,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 100,
      name: "Oracle",
      total: 13,
      level_1: 11,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 4,
      name: "PHP",
      total: 13,
      level_1: 8,
      level_2: 1,
      level_3: 0,
      level_4: 3,
      level_5: 1,
    },
    {
      stack_id: 2633,
      name: "Microsoft PPT",
      total: 12,
      level_1: 11,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2570,
      name: "SQL",
      total: 12,
      level_1: 7,
      level_2: 2,
      level_3: 1,
      level_4: 1,
      level_5: 1,
    },
    {
      stack_id: 5923,
      name: "Axure",
      total: 12,
      level_1: 10,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6658,
      name: "PRD",
      total: 12,
      level_1: 8,
      level_2: 2,
      level_3: 1,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 95,
      name: "R Language",
      total: 11,
      level_1: 8,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 2,
    },
    {
      stack_id: 49,
      name: "Apache Tomcat",
      total: 10,
      level_1: 8,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 2607,
      name: "Microsoft Office Visio",
      total: 10,
      level_1: 10,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 11,
      name: "Python",
      total: 10,
      level_1: 5,
      level_2: 4,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2646,
      name: "XMind",
      total: 9,
      level_1: 8,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2623,
      name: "Microsoft Excel",
      total: 8,
      level_1: 7,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2211,
      name: "JIRA",
      total: 7,
      level_1: 7,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2247,
      name: "Adobe Illustrator",
      total: 6,
      level_1: 4,
      level_2: 2,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2585,
      name: "TCP/IP",
      total: 6,
      level_1: 6,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2591,
      name: "MyBatis",
      total: 6,
      level_1: 5,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 922,
      name: "Postman",
      total: 6,
      level_1: 5,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 27,
      name: "Django",
      total: 6,
      level_1: 4,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 6428,
      name: "交互设计",
      total: 5,
      level_1: 4,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6667,
      name: "竞品分析",
      total: 5,
      level_1: 4,
      level_2: 0,
      level_3: 1,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 10,
      name: "Angular",
      total: 5,
      level_1: 4,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 2657,
      name: "统计学",
      total: 5,
      level_1: 5,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6324,
      name: "SPSS",
      total: 5,
      level_1: 3,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 877,
      name: "Kafka",
      total: 5,
      level_1: 4,
      level_2: 0,
      level_3: 1,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 924,
      name: "Elasticsearch",
      total: 5,
      level_1: 5,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2590,
      name: "Shell",
      total: 5,
      level_1: 5,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6419,
      name: "Scrum",
      total: 5,
      level_1: 4,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 55,
      name: "Microsoft SQL Server",
      total: 5,
      level_1: 3,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 6,
      name: "jQuery",
      total: 5,
      level_1: 5,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6467,
      name: "需求管理",
      total: 5,
      level_1: 4,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 64,
      name: "C++",
      total: 4,
      level_1: 3,
      level_2: 0,
      level_3: 0,
      level_4: 1,
      level_5: 0,
    },
    {
      stack_id: 12,
      name: "React",
      total: 4,
      level_1: 3,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 126,
      name: "Pandas",
      total: 4,
      level_1: 1,
      level_2: 3,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 16,
      name: "MongoDB",
      total: 4,
      level_1: 4,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6287,
      name: "Microsoft Project",
      total: 4,
      level_1: 4,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6359,
      name: "数据分析思维",
      total: 4,
      level_1: 4,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 5560,
      name: "Robot Framework",
      total: 4,
      level_1: 4,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 3635,
      name: "Apache",
      total: 3,
      level_1: 3,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2624,
      name: "Microsoft Word",
      total: 3,
      level_1: 3,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2582,
      name: "Memcached",
      total: 3,
      level_1: 3,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2558,
      name: "Canvas",
      total: 3,
      level_1: 3,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 56,
      name: "TypeScript",
      total: 3,
      level_1: 3,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2655,
      name: "数据分析",
      total: 3,
      level_1: 3,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 47,
      name: "Flask",
      total: 3,
      level_1: 2,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2636,
      name: "Matplotlib",
      total: 3,
      level_1: 2,
      level_2: 0,
      level_3: 1,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 1742,
      name: "Zabbix",
      total: 3,
      level_1: 3,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 3770,
      name: "gRPC",
      total: 3,
      level_1: 3,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 79,
      name: "Hadoop",
      total: 2,
      level_1: 2,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2596,
      name: "Flutter",
      total: 2,
      level_1: 2,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 3178,
      name: "Vuex",
      total: 2,
      level_1: 2,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 3441,
      name: "ElementUI",
      total: 2,
      level_1: 2,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6572,
      name: "2D&3D数据开发工具",
      total: 2,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 1,
    },
    {
      stack_id: 1605,
      name: "Jenkins",
      total: 2,
      level_1: 2,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 1704,
      name: "JUnit",
      total: 2,
      level_1: 2,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2600,
      name: "Golang",
      total: 2,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2562,
      name: "HTTP/HTTPS",
      total: 2,
      level_1: 2,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 299,
      name: "Druid",
      total: 2,
      level_1: 2,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6423,
      name: "DevOps",
      total: 2,
      level_1: 1,
      level_2: 1,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 30,
      name: "Laravel",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 887,
      name: "Tornado",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6608,
      name: "pyecharts",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2196,
      name: "Eclipse",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6305,
      name: "python auto office",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6662,
      name: "UCD",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 4623,
      name: "SAS",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6669,
      name: "需求分析",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6441,
      name: "Paxos",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 40,
      name: "RabbitMQ",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 123,
      name: "Kotlin",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2954,
      name: "CoreData",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6610,
      name: "黑盒测试",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6681,
      name: "数据库原理",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2641,
      name: "Data Struct",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6564,
      name: "分布式架构",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 2656,
      name: "数据可视化",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 6422,
      name: "微服务",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 4727,
      name: "JMeter",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 53,
      name: "React Native",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 1634,
      name: "Kubernetes",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
    {
      stack_id: 35,
      name: "C#",
      total: 1,
      level_1: 1,
      level_2: 0,
      level_3: 0,
      level_4: 0,
      level_5: 0,
    },
  ],
  config: {
    xAxis: { name: "测评人数" },
    yAxis: { name: "技能点", type: "value", inverse: true, field_name: "name" },
    height: 500,
    series: [
      { name: "了解", stack: true, field_name: "level_1" },
      { name: "熟悉", stack: true, field_name: "level_2" },
      { name: "掌握", stack: true, field_name: "level_3" },
      { name: "精通", stack: true, field_name: "level_4" },
      { name: "专家", stack: true, field_name: "level_5" },
    ],
    showGrid: true,
    showZoom: true,
    typeName: "条形图",
    widthNum: 6,
    showLegend: true,
    showTooltip: true,
  },
};
