export default {
  params: [
    {
      stack_id: 1,
      stack_name: "Bootstrap",
      eva_count: 77,
      eva_people: 34,
      score: 134.78,
    },
    {
      stack_id: 2,
      stack_name: "Nginx",
      eva_count: 34,
      eva_people: 14,
      score: 144.18,
    },
    {
      stack_id: 3,
      stack_name: "JavaScript",
      eva_count: 94,
      eva_people: 49,
      score: 120.37,
    },
    {
      stack_id: 4,
      stack_name: "PHP",
      eva_count: 36,
      eva_people: 13,
      score: 116.89,
    },
    {
      stack_id: 5,
      stack_name: "Node.js",
      eva_count: 21,
      eva_people: 15,
      score: 105.76,
    },
    {
      stack_id: 6,
      stack_name: "jQuery",
      eva_count: 11,
      eva_people: 5,
      score: 67.82,
    },
    {
      stack_id: 8,
      stack_name: "HTML5",
      eva_count: 74,
      eva_people: 30,
      score: 116.18,
    },
    {
      stack_id: 9,
      stack_name: "MySQL",
      eva_count: 129,
      eva_people: 51,
      score: 135.28,
    },
    {
      stack_id: 10,
      stack_name: "Angular",
      eva_count: 5,
      eva_people: 5,
      score: 169.8,
    },
    {
      stack_id: 11,
      stack_name: "Python",
      eva_count: 21,
      eva_people: 10,
      score: 88.14,
    },
    {
      stack_id: 12,
      stack_name: "React",
      eva_count: 5,
      eva_people: 4,
      score: 114.4,
    },
    {
      stack_id: 14,
      stack_name: "Redis",
      eva_count: 43,
      eva_people: 23,
      score: 123.3,
    },
    {
      stack_id: 16,
      stack_name: "MongoDB",
      eva_count: 4,
      eva_people: 4,
      score: 98.75,
    },
    {
      stack_id: 17,
      stack_name: "Java",
      eva_count: 26,
      eva_people: 16,
      score: 120.58,
    },
    {
      stack_id: 27,
      stack_name: "Django",
      eva_count: 7,
      eva_people: 6,
      score: 193.14,
    },
    {
      stack_id: 30,
      stack_name: "Laravel",
      eva_count: 2,
      eva_people: 1,
      score: 40,
    },
    {
      stack_id: 35,
      stack_name: "C#",
      eva_count: 1,
      eva_people: 1,
      score: 38,
    },
    {
      stack_id: 40,
      stack_name: "RabbitMQ",
      eva_count: 1,
      eva_people: 1,
      score: 44,
    },
    {
      stack_id: 42,
      stack_name: "Less",
      eva_count: 20,
      eva_people: 14,
      score: 138.75,
    },
    {
      stack_id: 47,
      stack_name: "Flask",
      eva_count: 3,
      eva_people: 3,
      score: 128,
    },
    {
      stack_id: 48,
      stack_name: "Vue.js",
      eva_count: 19,
      eva_people: 17,
      score: 185.79,
    },
    {
      stack_id: 49,
      stack_name: "Apache Tomcat",
      eva_count: 12,
      eva_people: 10,
      score: 151.92,
    },
    {
      stack_id: 52,
      stack_name: "Spring",
      eva_count: 17,
      eva_people: 14,
      score: 155.59,
    },
    {
      stack_id: 53,
      stack_name: "React Native",
      eva_count: 1,
      eva_people: 1,
      score: 80,
    },
    {
      stack_id: 55,
      stack_name: "Microsoft SQL Server",
      eva_count: 8,
      eva_people: 5,
      score: 161.88,
    },
    {
      stack_id: 56,
      stack_name: "TypeScript",
      eva_count: 4,
      eva_people: 3,
      score: 96.5,
    },
    {
      stack_id: 64,
      stack_name: "C++",
      eva_count: 4,
      eva_people: 4,
      score: 207.25,
    },
    {
      stack_id: 79,
      stack_name: "Hadoop",
      eva_count: 3,
      eva_people: 2,
      score: 106.67,
    },
    {
      stack_id: 80,
      stack_name: "Spring Boot",
      eva_count: 14,
      eva_people: 13,
      score: 185.71,
    },
    {
      stack_id: 95,
      stack_name: "R Language",
      eva_count: 16,
      eva_people: 11,
      score: 175.5,
    },
    {
      stack_id: 100,
      stack_name: "Oracle",
      eva_count: 18,
      eva_people: 13,
      score: 110.22,
    },
    {
      stack_id: 123,
      stack_name: "Kotlin",
      eva_count: 1,
      eva_people: 1,
      score: 69,
    },
    {
      stack_id: 126,
      stack_name: "Pandas",
      eva_count: 5,
      eva_people: 4,
      score: 156,
    },
    {
      stack_id: 299,
      stack_name: "Druid",
      eva_count: 3,
      eva_people: 2,
      score: 97.33,
    },
    {
      stack_id: 877,
      stack_name: "Kafka",
      eva_count: 11,
      eva_people: 5,
      score: 89.64,
    },
    {
      stack_id: 887,
      stack_name: "Tornado",
      eva_count: 2,
      eva_people: 1,
      score: 46,
    },
    {
      stack_id: 922,
      stack_name: "Postman",
      eva_count: 11,
      eva_people: 6,
      score: 99.09,
    },
    {
      stack_id: 924,
      stack_name: "Elasticsearch",
      eva_count: 6,
      eva_people: 5,
      score: 105.33,
    },
    {
      stack_id: 1599,
      stack_name: "Git",
      eva_count: 37,
      eva_people: 31,
      score: 115.95,
    },
    {
      stack_id: 1600,
      stack_name: "Docker",
      eva_count: 17,
      eva_people: 16,
      score: 163,
    },
    {
      stack_id: 1605,
      stack_name: "Jenkins",
      eva_count: 2,
      eva_people: 2,
      score: 94,
    },
    {
      stack_id: 1607,
      stack_name: "webpack",
      eva_count: 21,
      eva_people: 18,
      score: 140.71,
    },
    {
      stack_id: 1634,
      stack_name: "Kubernetes",
      eva_count: 2,
      eva_people: 1,
      score: 68,
    },
    {
      stack_id: 1704,
      stack_name: "JUnit",
      eva_count: 5,
      eva_people: 2,
      score: 97.6,
    },
    {
      stack_id: 1742,
      stack_name: "Zabbix",
      eva_count: 3,
      eva_people: 3,
      score: 134.67,
    },
    {
      stack_id: 2196,
      stack_name: "Eclipse",
      eva_count: 2,
      eva_people: 1,
      score: 54.5,
    },
    {
      stack_id: 2211,
      stack_name: "JIRA",
      eva_count: 13,
      eva_people: 7,
      score: 88.69,
    },
    {
      stack_id: 2225,
      stack_name: "Sketch",
      eva_count: 58,
      eva_people: 31,
      score: 108.98,
    },
    {
      stack_id: 2236,
      stack_name: "Adobe Photoshop",
      eva_count: 59,
      eva_people: 33,
      score: 111.53,
    },
    {
      stack_id: 2247,
      stack_name: "Adobe Illustrator",
      eva_count: 9,
      eva_people: 6,
      score: 113.33,
    },
    {
      stack_id: 2553,
      stack_name: "CSS3",
      eva_count: 24,
      eva_people: 19,
      score: 175.88,
    },
    {
      stack_id: 2554,
      stack_name: "Linux",
      eva_count: 28,
      eva_people: 19,
      score: 123.46,
    },
    {
      stack_id: 2558,
      stack_name: "Canvas",
      eva_count: 3,
      eva_people: 3,
      score: 88.67,
    },
    {
      stack_id: 2562,
      stack_name: "HTTP/HTTPS",
      eva_count: 2,
      eva_people: 2,
      score: 83.5,
    },
    {
      stack_id: 2570,
      stack_name: "SQL",
      eva_count: 17,
      eva_people: 12,
      score: 165.71,
    },
    {
      stack_id: 2582,
      stack_name: "Memcached",
      eva_count: 4,
      eva_people: 3,
      score: 48.25,
    },
    {
      stack_id: 2585,
      stack_name: "TCP/IP",
      eva_count: 8,
      eva_people: 6,
      score: 79.63,
    },
    {
      stack_id: 2590,
      stack_name: "Shell",
      eva_count: 7,
      eva_people: 5,
      score: 80.71,
    },
    {
      stack_id: 2591,
      stack_name: "MyBatis",
      eva_count: 6,
      eva_people: 6,
      score: 122.17,
    },
    {
      stack_id: 2592,
      stack_name: "Spring Cloud",
      eva_count: 20,
      eva_people: 16,
      score: 143.85,
    },
    {
      stack_id: 2596,
      stack_name: "Flutter",
      eva_count: 3,
      eva_people: 2,
      score: 92,
    },
    {
      stack_id: 2600,
      stack_name: "Golang",
      eva_count: 2,
      eva_people: 2,
      score: 44,
    },
    {
      stack_id: 2607,
      stack_name: "Microsoft Office Visio",
      eva_count: 10,
      eva_people: 10,
      score: 43.9,
    },
    {
      stack_id: 2623,
      stack_name: "Microsoft Excel",
      eva_count: 9,
      eva_people: 8,
      score: 99.11,
    },
    {
      stack_id: 2624,
      stack_name: "Microsoft Word",
      eva_count: 7,
      eva_people: 3,
      score: 73.57,
    },
    {
      stack_id: 2633,
      stack_name: "Microsoft PPT",
      eva_count: 19,
      eva_people: 12,
      score: 100.05,
    },
    {
      stack_id: 2636,
      stack_name: "Matplotlib",
      eva_count: 3,
      eva_people: 3,
      score: 154.67,
    },
    {
      stack_id: 2641,
      stack_name: "Data Struct",
      eva_count: 1,
      eva_people: 1,
      score: 29,
    },
    {
      stack_id: 2643,
      stack_name: "Wechat App",
      eva_count: 1,
      eva_people: 1,
      score: 129,
    },
    {
      stack_id: 2646,
      stack_name: "XMind",
      eva_count: 14,
      eva_people: 9,
      score: 84.29,
    },
    {
      stack_id: 2655,
      stack_name: "数据分析",
      eva_count: 4,
      eva_people: 3,
      score: 44,
    },
    {
      stack_id: 2656,
      stack_name: "数据可视化",
      eva_count: 1,
      eva_people: 1,
      score: 142,
    },
    {
      stack_id: 2657,
      stack_name: "统计学",
      eva_count: 5,
      eva_people: 5,
      score: 119.8,
    },
    {
      stack_id: 2954,
      stack_name: "CoreData",
      eva_count: 2,
      eva_people: 1,
      score: 82,
    },
    {
      stack_id: 3178,
      stack_name: "Vuex",
      eva_count: 2,
      eva_people: 2,
      score: 68,
    },
    {
      stack_id: 3441,
      stack_name: "ElementUI",
      eva_count: 2,
      eva_people: 2,
      score: 47,
    },
    {
      stack_id: 3635,
      stack_name: "Apache",
      eva_count: 4,
      eva_people: 3,
      score: 90.5,
    },
    {
      stack_id: 3770,
      stack_name: "gRPC",
      eva_count: 3,
      eva_people: 3,
      score: 81,
    },
    {
      stack_id: 4623,
      stack_name: "SAS",
      eva_count: 1,
      eva_people: 1,
      score: 110,
    },
    {
      stack_id: 4727,
      stack_name: "JMeter",
      eva_count: 3,
      eva_people: 1,
      score: 46.67,
    },
    {
      stack_id: 5560,
      stack_name: "Robot Framework",
      eva_count: 4,
      eva_people: 4,
      score: 52.75,
    },
    {
      stack_id: 5923,
      stack_name: "Axure",
      eva_count: 20,
      eva_people: 12,
      score: 82.7,
    },
    {
      stack_id: 6287,
      stack_name: "Microsoft Project",
      eva_count: 7,
      eva_people: 4,
      score: 67.71,
    },
    {
      stack_id: 6305,
      stack_name: "python auto office",
      eva_count: 2,
      eva_people: 1,
      score: 17,
    },
    {
      stack_id: 6324,
      stack_name: "SPSS",
      eva_count: 7,
      eva_people: 5,
      score: 129.86,
    },
    {
      stack_id: 6359,
      stack_name: "数据分析思维",
      eva_count: 6,
      eva_people: 4,
      score: 67.5,
    },
    {
      stack_id: 6419,
      stack_name: "Scrum",
      eva_count: 11,
      eva_people: 5,
      score: 79.09,
    },
    {
      stack_id: 6422,
      stack_name: "微服务",
      eva_count: 1,
      eva_people: 1,
      score: 77,
    },
    {
      stack_id: 6423,
      stack_name: "DevOps",
      eva_count: 2,
      eva_people: 2,
      score: 161.5,
    },
    {
      stack_id: 6428,
      stack_name: "交互设计",
      eva_count: 5,
      eva_people: 5,
      score: 60.6,
    },
    {
      stack_id: 6441,
      stack_name: "Paxos",
      eva_count: 1,
      eva_people: 1,
      score: 88,
    },
    {
      stack_id: 6467,
      stack_name: "需求管理",
      eva_count: 5,
      eva_people: 5,
      score: 54.8,
    },
    {
      stack_id: 6556,
      stack_name: "软件质量管理",
      eva_count: 1,
      eva_people: 1,
      score: 113,
    },
    {
      stack_id: 6564,
      stack_name: "分布式架构",
      eva_count: 1,
      eva_people: 1,
      score: 9,
    },
    {
      stack_id: 6572,
      stack_name: "2D&3D数据开发工具",
      eva_count: 2,
      eva_people: 2,
      score: 272,
    },
    {
      stack_id: 6608,
      stack_name: "pyecharts",
      eva_count: 1,
      eva_people: 1,
      score: 111,
    },
    {
      stack_id: 6610,
      stack_name: "黑盒测试",
      eva_count: 1,
      eva_people: 1,
      score: 169,
    },
    {
      stack_id: 6658,
      stack_name: "PRD",
      eva_count: 21,
      eva_people: 12,
      score: 103.43,
    },
    {
      stack_id: 6662,
      stack_name: "UCD",
      eva_count: 1,
      eva_people: 1,
      score: 119,
    },
    {
      stack_id: 6667,
      stack_name: "竞品分析",
      eva_count: 8,
      eva_people: 5,
      score: 95.5,
    },
  ],
  config: {
    xAxis: { name: "测评人数", field_name: "eva_people" },
    yAxis: { name: "测评次数", field_name: "eva_count" },
    height: 500,
    series: { groupField: "" },
    toolbox: {
      restore: true,
      dataView: false,
      dataZoom: true,
      saveAsImage: false,
    },
    typeName: "散点图",
    widthNum: 6,
    showLabel: true,
    showLegend: true,
    symbolSize: { name: "平均得分", zoom: "25", field: "score" },
    showTooltip: true,
    item_name_field: "stack_name",
  },
};
